# This is a basic workflow to help you get started with Actions

name: CI

env:
  SOURCE_DIR: ${{ github.workspace }}

on:
  [push, pull_request]

jobs:
  unit-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: JAVA VERSION 11 SETUP
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'adopt'
    
      - name: Add rights
        run: chmod +x $SOURCE_DIR/FamilyFinanceService/gradlew
    
      - name: Unit-tests
        run: $SOURCE_DIR/FamilyFinanceService/gradlew testDebugUnitTest
          
      - name: Test reporting
        uses: asadmansr/android-test-report-action@v1.2.0
        if: ${{ always() }}
