# This is a basic workflow to help you get started with Actions

name: CI

env:
  SOURCE_DIR: ${{ github.workspace }}

on:
  [push, pull_request]

jobs:
  unit-test:
    runs-on: ubuntu-latest

    steps:
      - name: Add rights
        run: ls
      - name: Add rights 2
        run: cd $SOURCE_DIR && ls
            
